### ISSUE TITLE
Document filtering algorithm

### ISSUE THREAD

**Issue by rexagod** [publiclab/matcher-cli#11]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** Add to README the process the algorithm that's used to detect and filter commands below. We recommend you to run the library and set up breakpoints to familiarize yourself with this!
https://github.com/publiclab/matcher-cli/blob/0bf71868eca76bfc25c8e277bf318257bb8edc6f/matcher.js#L27-L38
 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by spassaro80** [comment]
Hi, can I pick this one?

thx

**Comment by rexagod** [comment]
Sure! Go ahead!

Pranshu Srivastava | @rexagod

**Comment by aishukamble** [comment]
Hi, New contributor here. want to pick it.

**Comment by rexagod** [comment]
Sure! Go ahead!


Pranshu Srivastava | @rexagod

**Comment by spassaro80** [comment]
Hi

I've tried to run matcher.js in node.js but it by it gives me this error. I'm sure I'm doing something wrong, I'll try to find what it is :).

Server's up @ http://127.0.0.1:9990

(node:7708) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:9990/demo/
    at navigate (C:\Users\00070261\matcher-cli\node_modules\puppeteer\lib\FrameManager.js:121:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\00070261\matcher-cli\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.goto (C:\Users\00070261\matcher-cli\node_modules\puppeteer\lib\Page.js:629:49)
    at Page.<anonymous> (C:\Users\00070261\matcher-cli\node_modules\puppeteer\lib\helper.js:111:23)
    at invoke (C:\Users\00070261\matcher-cli\src\matcher-summon.js:56:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SantruptaMishra98** [comment]
hi can I pick this up?

**Comment by bermylle** [comment]
Hi can i pick this up? Or is it already taken :)

**Comment by stefanosu** [comment]
Hi is this issue still being worked on? I would like to help if any is needed? Thanks, first-time contributor here.
