### ISSUE TITLE
Terser failing

### ISSUE THREAD

**Issue by rexagod** [publiclab/matcher-cli#3]
```
matcher-cli/matcher.unc.min.js:8898
exports.default = global.fetch.bind(global);
                               ^

TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:8898:32)
    at Object.54 (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:8903:4)
    at o (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:1:327)
    at /mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:1:378
    at Object.<anonymous> (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:8686:15)
    at Object.47.../.env_vars.json (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:8757:4)
    at Object.93.../.env_vars.json (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:18761:21)
    at o (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:1:327)
    at /mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:1:378
    at Object.91.../.env_vars.json (/mnt/c/Users/Rexagod/Desktop/matcher-cli/matcher.unc.min.js:18636:18)
```

**Comment by rexagod** [comment]
Fixed, included missing terser peer deps into build.
